name: flutter-tag
# 👇 这里增加权限，传给被调用的复用工作流
permissions:
  contents: write
  pull-requests: read

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: Songmlgm/rustdesk-songmlgm/.github/workflows/flutter-build.yml@a5cff6c4be813a64a80b4abc734f49799bef358c
    # 不要在这里写 permissions，要写在 workflow 顶层！
